### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by maganius** [upatra/polaris-vue#9]
How install this library?

I installed the package but there is not a dist folder and npm throw this error:

```
Module not found: Error: Can't resolve '@upatra/polaris-vue'
```

**Comment by MurmeltierS** [comment]
Same for me

**Comment by clayzar** [comment]
Since the dist folder is needed, I forked the repo. I then ran the command `npm run build-bundle` because of the script defined in package.json, and removed the /dist folder from the .gitignore. I've adapted the readme with updated installation instructions. Feel free to try it out.

https://github.com/clayzar/polaris-vue

**Comment by neihc** [comment]
Thank you guys,
I published a version to fix this issue
